version: "3"

services:
  dev:
    build:
      context: .
      target: builder
    container_name: queryhub-frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    command: npm run dev -- --host
