version: "3"

services:
  frontend:
    build: .
    container_name: queryhub-frontend
    ports:
      - "3000:80"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    command: sh -c "npm run build && nginx -g 'daemon off;'"

  dev:
    build:
      context: .
      target: builder
    container_name: queryhub-frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    command: npm run dev -- --host
