name: Run Unit Tests

on:
  push:
    branches:
      - main
      - dev
      - connectors
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      # EMBEDDING_MODEL: "text-embedding-004"
      # FRONTEND_ORIGIN: "https://myfrontend.example.com"
      # LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
      # GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Set up Python
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      # 3️⃣ Install dependencies
      - name: Install dependencies
        working-directory: tests
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-mock


      # 4️⃣ Run pytest for all test folders
      - name: Run unit tests
        working-directory: tests
        run: |
          pytest -v --maxfail=1 --disable-warnings agents backend connectors

